import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import style from "@/styles/header.module.scss"
import Image from "next/image";
const myFont = localFont({
  src: '../public/fonts/AppleSDGothicNeoEB.ttf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "SongYoungJun po",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <header className={style.header}>
          <Image src={"/image/구름하늘.jpg"} fill={true} alt={"구름"}/>
        </header>
        {children}
        <footer className={style.foot}>
        </footer>
        </body>
    </html>
  );
}
